sudo: required
dist: trusty

branches:
  only:
    - master
    - develop

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script: docker -v
    - stage: push
      script: docker-compose -v
