version: '3'

services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/postgresql:/var/lib/postgresql/data
    restart: always
    enviroment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  data:
    driver: local

networks:
  app:
    driver: bridge