version: '3'

services:
  nodejs:
    build: .
    container_name: meme_nodejs
    volumes:
      - ./app:/var/www/backend/app
      - ./node_modules:/var/www/node_modules
    ports:
      - ${SOCKET_PORT}:${SOCKET_PORT} # SOCKET
      - ${KUE_PORT}:${KUE_PORT} # KUE
      - ${REST_PORT}:${REST_PORT} # REST
    networks:
      - app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:10
    container_name: meme_postgres
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./docker/data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app
  redis:
    image: redis:3.2
    container_name: meme_redis
    volumes:
      - ./docker/data/redis:/data/redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app

networks:
  app:
    driver: bridge