version: '3'

services:
  nodejs:
    build: .
    container_name: meme_nodejs
    volumes:
      - ./:/var/www/backend
    ports:
      - 8080:8080
    networks:
      - app
    depends_on:
      - database
  database:
    image: postgres:10
    container_name: meme_database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app

networks:
  app:
    driver: bridge