version: '3'

services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/postgresql:/var/lib/postgresql/data
    restart: always
    enviroment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DB}
    networks:
      - app
  redis:
    image: redis:3.0-alpine
    ports:
      - "6379:6379"
    netwokrs:
      - app

volumes:
  data:
    driver: local

networks:
  app:
    driver: bridge