version: '3'

services:
  nodejs:
    build: .
    container_name: meme_nodejs
    volumes:
      - ./app:/var/www/backend/app
      - ./node_modules:/var/www/node_modules
    ports:
      - 8000:8000 # SOCKET
      - 8001:8001 # KUE
      - 8080:8080 # REST
    networks:
      - app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:10
    container_name: meme_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app
  redis:
    image: redis:3.2
    container_name: meme_redis
    volumes:
      - ./docker/data/redis:/data/redis
    ports:
      - "6379:6379"
    networks:
      - app

networks:
  app:
    driver: bridge