DROP TABLE IF EXISTS games CASCADE;
CREATE TABLE games(
            id serial PRIMARY KEY,
            status text DEFAULT 'prepare',
            mode_id INTEGER REFERENCES game_modes(id) ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS played_memes CASCADE;
CREATE TABLE played_memes(
    id serial PRIMARY KEY,
    game_id INTEGER NOT NULL REFERENCES games(id) ON UPDATE CASCADE ON DELETE CASCADE,
    meme_id INTEGER NOT NULL REFERENCES meme_storage(id) ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS playres CASCADE;
CREATE TABLE playres(
    id serial PRIMARY KEY,
    game_id INTEGER NOT NULL REFERENCES games(id) ON UPDATE CASCADE ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS winer_memes CASCADE;
CREATE TABLE winer_memes(
    id serial PRIMARY KEY,
    game_id INTEGER NOT NULL REFERENCES games(id) ON UPDATE CASCADE ON DELETE CASCADE,
    meme_id INTEGER NOT NULL REFERENCES meme_storage(id) ON UPDATE CASCADE ON DELETE CASCADE
);