module.exports = {
    CREATE_GAME: 'CREATE_GAME',
    START_GAME: 'START_GAME',
    CONNECT_TO_GAME_CLIENT: 'CONNECT_TO_GAME_CLIENT',
    CONNECT_TO_GAME_SERVER: 'CONNECT_TO_GAME_SERVER',
    LEAVE_FROM_GAME: 'LEAVE_FROM_GAME',
    CHOOSE_MEM: 'CHOOSE_MEM',
    GET_MEM_PAIR: 'GET_MEM_PAIR',
    NEW_PAIR: 'NEW_PAIR',
    PAIR_WINNER: 'PAIR_WINNER',
};
