module.exports = {
    CREATE_GAME: 'CREATE_GAME',
    START_GAME: 'START_GAME',
    CONNECT_TO_GAME_REQUEST: 'CONNECT_TO_GAME_REQUEST',
    CONNECT_TO_GAME_SUCCESS: 'CONNECT_TO_GAME_SUCCESS',
    LEAVE_FROM_GAME: 'LEAVE_FROM_GAME',
    CHOOSE_MEM_REQUEST: 'CHOOSE_MEM_REQUEST',
    CHOOSE_MEM_SUCCESS: 'CHOOSE_MEM_SUCCESS',    
    GET_MEM_PAIR_REQUEST: 'GET_MEM_PAIR_REQUEST',
    GET_MEM_PAIR_SUCCESS: 'GET_MEM_PAIR_SUCCESS',
    NEW_PAIR: 'NEW_PAIR',
    PAIR_WINNER: 'PAIR_WINNER',
};
